[default]
extend-ignore-re = [
    # Ignore lines that end with `// spellchecker:disable-line`
    '(?Rm)^.*(#|//)\s*spellchecker:disable-line$',
    # Ignore the line after `// spellchecker:ignore-next-line`
    '(#|//)\s*spellchecker:ignore-next-line\n.*',
    # Ignore blocks between `// spellchecker:off` and `// spellchecker:on`
    '(?s)(#|//)\s*spellchecker:off.*?\n\s*(#|//)\s*spellchecker:on',
]

[type.markdown]
extend-glob = ["*.md"]
extend-ignore-re = [
    '(?s)\*\*Deutsch\*\*.*?(\n\n|\z)',
    '(?s)WICHTIG:.*?(\n\n|\z)',
]
