name: PHP_CodeSniffer
on: push
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer, cs2pr
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Detect coding standard violations
        run: ./vendor/bin/phpcs -n -q